config/routes.rb
Rails.application.routes.draw do

	RottenMangoes::Application.routes.draw do

		resources :movies do
			resources :reviews, only: [:new, :create]
			
		end
		resources :users, only: [:new, :create, :show, :index]
		resource :session, only: [:new, :create, :destroy]

		get '/user/:id/wishlist', to: 'users#wishlist', as: :wishlist

		root to: 'movies#index'

		namespace :admin do
			resources :users
			resources :impersonators, only: [:new, :create, :destroy]	
		end
	end


end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :reviews
	has_many :movies
  has_secure_password
  scope :search, -> (query){  where("firstname like ? or lastname like ?", "%#{query}%", "%#{query}%")}
	def full_name
		"#{firstname} #{lastname}"
	end

	

		
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < UsersController 

	before_action :find_user, only: [:show, :edit]


	def index
		# session[:user_id] = session[:admin_id]
		session[:user_id] = session[:admin_id].to_i if session[:admin_id]
		session[:admin_id] = nil
		@users = User.all.page(params[:page]).per(5)
	end	

	def show
	end

  def edit
  end

  def update
		@user = User.find(params[:id])

  	if @user.update_attributes(user_params)
  		redirect_to admin_user_path(@user), notice: "Success"
  	else
  		render :edit
  	end
  end

	def find_user 
		@user = User.find(params[:id])
	end

	def user_params
		params.require(:user).permit(:email, :firstname, :lastname, :admin)
	end

	def destroy
		#email user

		@user = User.find(params[:id])
		UserMailer.delete_user_email(@user).deliver
		@user.destroy
		redirect_to admin_users_path
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@user = User.new
  end

  def show
    @user = User.find(params[:id])
    @movies = @user.movies.watched.reverse
  end

  def wishlist
    @user = User.find(params[:id])
    @movies = @user.movies.wishlist.reverse
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
  		session[:user_id] = @user.id
  		redirect_to movies_path, notice: "Welcome aboard, #{@user.firstname}!"
  	else
  		render :new
  	end
  end

  def index
    searches = params[:user_query].split(" ")
    users = User.all
    searches.each do |search|
      users = users.search(search)
    end
    @users_found = users
    # @users_found = {data: users}.to_json
    # respond_to do |format|
      # format.json { render json: @users_found }
     # end
  end



  protected

  def user_params
  	params.require(:user).permit(:email, :firstname, :lastname, :password, :password_confirmation)
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/edit.html.erb
EDIT USER PAGE

<%= form_for [:admin, @user] do |f| %>
  <div>
    <%= f.label "firstname" %><br>
    <%= f.text_field "firstname" %>
  </div>
  <div>
    <%= f.label "lastname" %><br>
    <%= f.text_field "lastname" %>
  </div>
  <div>
    <%= f.label "email" %><br>
    <%= f.text_field "email" %>
  </div>
  <div class="field">
    <%= f.label "admin" %><br>
    <%= f.check_box :admin %>
  </div>
  <div>
    <%= f.submit "Submit" %> 
  </div>
<% end %>

app/views/admin/users/index.html.erb
ADMIN USERS MANAGEMENT
<%= paginate @users %>
<hr>
<% @users.each do |user| %>
	<p>
	<%= link_to user.firstname, admin_user_path(user) %>   <%= user.lastname %>   <%= user.email %> 
	<% if user.id != session[:user_id] %>
		<%= link_to "Ghost", admin_impersonators_path(ghost_id: user.id, admin_id: session[:user_id]), method: "POST" %>
	<% end %>
	</p>
<% end %>
<hr>

app/views/admin/users/show.html.erb
SHOW USER page
<%=@user.firstname%>
<div id="flash_messages">
  <% flash.each do |key, value| %>
    <%= content_tag(:div, value, :class => "flash #{key}") %>
  <% end %>
</div>
<%= link_to "edit", edit_admin_user_path %>
	<%= link_to "delete this user", admin_user_path, method: "DELETE"%>