config/routes.rb
Rails.application.routes.draw do

	RottenMangoes::Application.routes.draw do

		resources :movies do
			resources :reviews, only: [:new, :create]
			
		end
		resources :users, only: [:new, :create, :show, :index]
		resource :session, only: [:new, :create, :destroy]

		get '/user/:id/wishlist', to: 'users#wishlist', as: :wishlist

		root to: 'movies#index'

		namespace :admin do
			resources :users
			resources :impersonators, only: [:new, :create, :destroy]	
		end
	end


end

app/views/layouts/_footer.html.erb
<footer>
	<small>
		<% if current_user %>
			Signed in as <%= link_to current_user.full_name, user_path(current_user) %> 
				<% if mimicing? %>
					<%= link_to "UnGhost", admin_users_path  %>
				<% else %>

					<%= link_to "Log out", session_path("current"), method: :delete %>
				<% end %>
				
				<% if is_admin? %>
					<%= link_to "Admin page", admin_users_path %>
				<% end %>
		<% else %>

			<%= link_to "Log In", new_session_path %> | <%= link_to "Sign Up", new_user_path %>

		<% end %>
		<%= link_to "Home", movies_path %>
		
	</small>

</footer>

app/views/layouts/_header.html.erb
<h1><%= link_to "Rotten Mangoes", root_path %></h1>
<ul class="nav nav-pills">
	<% if session[:user_id] %>
		<li class="col-md-12"><%= link_to current_user.firstname , user_path(current_user)%></li>
		<li class="col-md-12"><%= link_to "Submit a movie!", new_movie_path %></li>
		<li class="col-md-12"><%= link_to "Log out", session_path("current"), method: :delete %></li>

	<% else %>
		<li><%= link_to "Log in", new_session_path %></li>
		<li><%= link_to "Sign up", new_user_path %></li>
	<% end %>

	<%= form_tag(users_path, :method => "get", id: "search-form") do %>
		<%= text_field_tag :user_query, params[:user_query], placeholder: "Search users" %>
		<% submit_tag "Search user", :name => nil%>
	<% end %>

	<%= form_tag(movies_path, :method => "get", id: "search-movies") do %>
		<%= text_field_tag :movie_query, params[:movie_query], placeholder: "Search movie reviews" %>
		<% submit_tag "Search movie", :name => nil %>
	<% end %>

</ul>

<!-- 	<%# form_tag(movies_path, :method => "get", id: "search-form") do %>
	  <%# text_field_tag :search, params[:search], placeholder: "Search" %>
	  <%# select_tag(:duration, options_for_select([
	                [],
	  							['minutes < 90', 1], 
	  							['90 < minutes < 120', 2], 
	  							['120 < minutes', 3]])) %>

	  <%# submit_tag "Search", :name => nil %>
	<%# end %> -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RottenMangoes</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% flash.each do |key, value| %>
	<%= content_tag(:div, value) %>
<% end %>
<div class="col-md-2">
	<%= render 'layouts/header' %>
</div >
<div class="col-md-10">
<%= yield %>
</div>
<%= render 'layouts/footer' %>
</body>
</html>